### ISSUE TITLE
ProcBots should use a configuration file, if available

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#45]
The configuration file is written in YAML and includes nesting for each hierarchy of bot.
For example, the top level class is the `ProcBot`, which is currently inherited by `GithubBot` (which knows how to deal with the Github API and events as an Integration) and which itself is inherited by `VersionBot`.
Therefore we can create a YAML file that is processed by the `ProcBot` class, but hold information for each of the children:
```
procbot:
    minimum_version: 0.3.2
    githubbot:
        versionbot:
            minimum_approvals: 2
            approved_reviewers:
                - lekkas
                - hedss
                - Page-
                - petrosagg
                - pimterry
            maintainers:
                - lekkas
                - hedss
```
There is a 'retrieveConfiguration()' method at the top level (which in `ProcBot` looks for a file path), that retrieves the configuration and then calls `processConfiguration()` which returns the processed config. `processConfiguration()` is itself not designed to be overriden and converts the YAML into an object.

In the flow for a dummy ProcBot child that does nothing, then, it would call `retrieveConfiguration()` which would return any suitable object.
In the flow for a `GithubBot` derived child, it calls `retrieveConfiguration()` which is overridden by `GithubBot` and takes a repo owner, name and branch. It then retrieves the configuration from this repo and calls it's parent `ProcBot` with `processConfiguration()` before returning it.

At each level, if a class understands that a particular property relates to a boolean (for example, `minimum_version`), it can determine the result of this and inject this as the value for the field in the returned object. This allows conditional tests to be performed on the configuration object to allow children to determine whether they should run or not.

In the above example then, `minimum_version` would be determined as `true` if the `ProcBot` running were `0.3.2` or above, or `false` otherwise.

**Comment by lurch** [comment]
> In the above example then, `minimum_version` would be determined as `true` if the `ProcBot` running were `0.3.2` or above, or `false` otherwise.

Hmm, but what if a ProcBot actually _needs_ the original `minimum_version` value? What if the 'booleanized result' was instead stored in `minimum_version_result` ? \*shrug\*

Does `processConfiguration()` do any 'flattening' of the YAML hierarchy, or is the nesting preserved? i.e. can VersionBot see the `minimum_version`, or is that accessible only by ProcBot?

If a YAML file stored configuration entries for multiple bots, e.g.
```yaml
procbot:
    minimum_version: 0.3.2
    githubbot:
        versionbot:
            minimum_approvals: 2
            approved_reviewers:
                - lekkas
                - hedss
                - Page-
                - petrosagg
                - pimterry
            maintainers:
                - lekkas
                - hedss
        monitorbot:
            timeout: 300
```
would VersionBot have access to the entire 'configuration tree', or would the MonitorBot settings be excluded?
