### ISSUE TITLE
PokeBot - A Github user reminder system

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#54]
Given a list of repositories in a config file:
```
procbot:
    githubbot:
        pokebot:
            repositories:
                - resin-io/resin-image-maker
                - resin-io/resin-builder
                - ...
            timeout: 3 days
```
ProdBot enumerates every open PR for a repository. It sets a timer based on the `timeout` value and then scans all the open PRs. Should a PR not have been touched for the last `timeout` value, then every reviewer and the author of the PR is 'poked' by mentioning them in a comment. The timeout then resets.

We could also allow dynamic timeouts for each repo, perhaps.

One implementation detail is the limit of non-state storage for ProcBots (indeed, ProcBots should never store state). Happily, this is not an issue for ProdBot, as  should it be restarted, it can scan all repos on startup and look for the last activity, then set a delta between when that occured and the `timeout` value to ensure it scans again at the correct interval.
